### ISSUE TITLE
Question: Are you able to use Intellij with this project?

### ISSUE THREAD

**Issue by javadba** [charleskorn/kaml#16]
I tried to use `kaml` in an unrelated project and was unable to make `Idea` happy with it. I have the latest version of Idea for macOS  `2019.3`. 

So I `git clone`d your repo to see how _it_ fares and see the same issues

![image](https://user-images.githubusercontent.com/410769/78617893-b2fce100-782d-11ea-8bce-b996afd431d5.png)

Have you found some magic to convince IJ to work with you? Care to share that magic? thx!

**Comment by charleskorn** [comment]
Hi @javadba! It should just work in IntelliJ - did you import it as a Gradle project?

**Comment by javadba** [comment]
Yes - I had created a new _Kotlin_ project.   But apparently it did not "take":

![createdKotlinButDidNotStick](https://user-images.githubusercontent.com/410769/78686489-f300aa00-78a7-11ea-97d9-48b8277372d8.png)

After adding kotlin facet and recompiling it's groovy now.  (oh ouch)

**Comment by javadba** [comment]
Actually no it still is broken. 

![kamlBuildFails](https://user-images.githubusercontent.com/410769/78687932-87b7d780-78a9-11ea-83bc-776c5dd3b98a.png)

**Comment by javadba** [comment]
So I have started from scratch. I blew away the .idea directory in project root dir and reopened the directory.  Idea detected this as a gradle project and did this:

![ideaDetectsGradle](https://user-images.githubusercontent.com/410769/78688862-8e931a00-78aa-11ea-9f82-f5fc92a42a7e.png)

![ideaAutoBuild](https://user-images.githubusercontent.com/410769/78688972-aff40600-78aa-11ea-8b97-25dd3c650a66.png)

![kamlSameErrorsInNewProject](https://user-images.githubusercontent.com/410769/78689625-648e2780-78ab-11ea-942a-24af604e182d.png)

Another issue is that the tests do show up as tests: but trying to run them is a noop: nothing happens.

![kamlSameErrorsInNewProject](https://user-images.githubusercontent.com/410769/78689943-b8990c00-78ab-11ea-9dc6-5f4778a37c66.png)

I am going to do something else now:  blow away  project /.idea directory and see if can explicitly import as kotlin.  I don't think this will help but i'm at the end of ideas.

![importKaml](https://user-images.githubusercontent.com/410769/78690452-4c6ad800-78ac-11ea-8383-335b4e271693.png)

But that did much worse than just opening the root directory and letting Idea figure it out:

![importKamlNoFrameworksDetected](https://user-images.githubusercontent.com/410769/78690455-4d036e80-78ac-11ea-8e0b-b9db44cb6ce4.png)

**Comment by charleskorn** [comment]
Hi @javadba, I've just tried opening a fresh clone of the project on my machine and I'm not running into any issues. These are the steps that I followed:

1. Clone project
2. In IntelliJ: File > Open, browse to `kaml` directory and open
3. Wait for IntelliJ to run Gradle sync for the first time

In order to run the tests from IntelliJ, you'll need to have the [Spek plugin](https://plugins.jetbrains.com/plugin/10915-spek-framework) installed.

**Comment by javadba** [comment]
That's what I did - multiple times.  I'm on Intellij 2019.3.4 using java 11 on macOS. Can you provide more info on what you are using

**Comment by javadba** [comment]
I am truly frustrated . Kotlin looks like a great language. But I can't use it due to gradle / build issues.

**Comment by javadba** [comment]
Can you please check `YamlWritingTest.kt` . See whether Intellij is able to find the `serializer` implicits in your project?  

![image](https://user-images.githubusercontent.com/410769/78760953-c34cb300-7936-11ea-9f8b-2fcbdc0b2a79.png)

Note that tests did run.  

![image](https://user-images.githubusercontent.com/410769/78761006-d8294680-7936-11ea-8a1d-7711945cd8f2.png)

**Comment by javadba** [comment]
Also when I right click in that testcase and select run it is a huge mess

![image](https://user-images.githubusercontent.com/410769/78761867-09eedd00-7938-11ea-8202-e7ac9a0492f0.png)

Remember: this is in the same project that built successfully via `gradle build` that was kicked off when doing `File | Open` .   I don't know why IJ can build/test initially for the new project but 

* the editor finds errors
* the individual test runner is _really_ unhappy : finding many serious compilation errors.

Even though `kotlin` was built by JetBrains I'm suspicious of the integration of Kotlin with Intellij

**Comment by javadba** [comment]
Runs fine `gradle test` from command line.   All signs point to some serious `Idea` problems.  Very curious if you were able to open the  `YamlWritingTest` in IJ , right click and `run` it.

**Comment by charleskorn** [comment]
> I'm on Intellij 2019.3.4 using java 11 on macOS. Can you provide more info on what you are using

I'm also using IntelliJ 2019.3.4 with Kotlin plugin version 1.3.71-release-IJ2019.3-1.

> Can you please check YamlWritingTest.kt . See whether Intellij is able to find the serializer implicits in your project?

Yep, it works fine for me.

> Note that tests did run.

That's just for the `buildSrc` project (additional code for the Gradle project), not the library's tests.

One last thing you might want to check: these are my settings in Preferences > Build, Execution, Deployment > Build Tools > Gradle - do you have the same settings?

![Screen Shot 2020-04-08 at 9 10 42 pm](https://user-images.githubusercontent.com/4017646/78777796-87205d80-79dd-11ea-9924-e7a892221eda.png)

If that isn't fruitful, I think you're going to need to get in touch with JetBrains (or perhaps ask for help in [the Kotlin Slack group](http://slack.kotlinlang.org) or one of [the other community groups](https://kotlinlang.org/community/)) - this seems to be an issue with your IntelliJ setup rather than an issue with Kaml, and I'm not sure I'll be able to help you any further sorry.

**Comment by javadba** [comment]
I give up. I'm shelving kotlin _just due to build tools_
