### ISSUE TITLE
Stops working when upgrading above 0.28.3

### ISSUE THREAD

**Issue by paalpri** [charleskorn/kaml#279]
### Describe the bug

Hi! 

Firstly, great work on the project!

We have been using the YAML parser for a bit of time now and it's been working great, but now we want to upgrade our dependencies and have a problem when trying to upgrade above 0.28.3. 

On 0.28.3 it works as usual, but any version number above that we are getting errors. 

We are experiencing the following error during compilation: 
` Unresolved reference: Yaml`

We are using a kotlin and maven project. And are getting errors when trying to import 'com.charleskorn.kaml.Yaml' as well. 

This is with no change in our code, only version number upgrade.

Let me know if there is need for more information.  

### Steps to reproduce

Kotlin and maven project.
Include This in your pom
`        <dependency>
            <groupId>com.charleskorn.kaml</groupId>
            <artifactId>kaml</artifactId>
            <version>0.29.0</version>
        </dependency>
`

Try to import   `import com.charleskorn.kaml.Yaml`
 
 Create a method and use a YAML.xxx method, like Yaml.default.decodeFromString("testing")
 
 This gives us import errors and unresolved reference errors. 

### Expected behaviour

Expect it to find the project and import correctly. 

### Actual behaviour

Error during import and Unresolved Reference during compilation. No error in pole file and jar files are downloaded during compilation. 

### Version information

```plain text
anything above 0.28.3 failes. 0.28.3 works.
```

**Comment by charleskorn** [comment]
Hi @paalpri, it's quite hard to debug this issue without a sample project that demonstrates the issue, as it could be any of a number of different things that is causing this. 

Are you able to share your project, or, alternatively, share a sample project that shows the same behaviour?

**Comment by charleskorn** [comment]
0.29.0 was the first version to be published using Kotlin's multiplatform project format.

I've never used Maven with a multiplatform library, so I'm not sure if Kaml would need to be referenced in a slightly different way to support this. For example, you may need to change `<artifactId>kaml</artifactId>` to `<artifactId>kaml-jvm</artifactId>`.

(Gradle automatically picks up the right variant of the library based on your target platform, which is why this just works for Gradle users.)
