### ISSUE TITLE
Maven Central has an empty JAR file

### ISSUE THREAD

**Issue by dkim19375** [charleskorn/kaml#346]
### Describe the bug

The versions `0.43.0` - latest (`0.49.0` as of writing this) only contain a 695 byte file containing only a `META-INF` folder.
The versions `0.29.0` - `0.42.0` contain the package `com.charleskorn.kaml`, but inside there are only `.kotlin_metadata` files.
So, the latest working version on Maven Central is `0.28.3` which is nearly 2 years old.

### Steps to reproduce

Go on https://mvnrepository.com/artifact/com.charleskorn.kaml/kaml/0.49.0 (and browse through the versions).
You can also see https://repo1.maven.org/maven2/com/charleskorn/kaml/kaml/0.49.0/ and notice how `kaml-0.49.0.jar` has only a 695 byte file
Somehow,
```gradle
compileOnly("com.charleskorn.kaml:kaml:0.49.0")
```
works... I haven't tested with `implementation` though

### Expected behaviour

https://repo1.maven.org/maven2/com/charleskorn/kaml/kaml/0.49.0/ having the correct jar file

### Actual behaviour

https://repo1.maven.org/maven2/com/charleskorn/kaml/kaml/0.49.0/ not having the correct jar file

### Version information

```plain text
0.49.0
```

**Comment by charleskorn** [comment]
Hi @dkim19375, this is expected behaviour. 

Kaml is a Kotlin Multiplatform project, although it only supports the JVM at present. As a result of being a multiplatform project, the `kaml` artefact on Maven Central contains only the metadata required for Gradle to resolve the appropriate platform-specific artefact (eg. `kaml-jvm`).

**Comment by dzikoysk** [comment]
In my case, after upgrading to the latest version, Gradle 8.1 didn't resolve `kaml-jvm` from `kaml`:

```
implementation("com.charleskorn.kaml:kaml:0.53.0")
```

I've migrated to:

```
implementation("com.charleskorn.kaml:kaml-jvm:0.53.0")
```

and it works, but is it the expected approach?

**Comment by charleskorn** [comment]
> In my case, after upgrading to the latest version, Gradle 8.1 didn't resolve `kaml-jvm` from `kaml`:
> 
> ```
> implementation("com.charleskorn.kaml:kaml:0.53.0")
> ```
> 
> I've migrated to:
> 
> ```
> implementation("com.charleskorn.kaml:kaml-jvm:0.53.0")
> ```
> 
> and it works, but is it the expected approach?
> 

Just to clarify: are you saying you needed to do this after upgrading Gradle? Or after upgrading kaml?

**Comment by dzikoysk** [comment]
After upgrading kaml from `0.49.0` to `0.53.0` on Gradle 8.1.

**Comment by charleskorn** [comment]
Are you able to share a sample project that demonstrates the issue? I've been using kaml with Gradle 8.1 without issue.

**Comment by dzikoysk** [comment]
I took a look on other multiplatform libraries, and it seems to be a thing with Kotlin Multiplatform that uses different API for dependencies by default:

* https://kotlinlang.org/docs/multiplatform-add-dependencies.html

If you want to use multiplatform library in regular jvm project, you should [use `-jvm` suffix](https://kotlinlang.org/docs/multiplatform-add-dependencies.html#kotlinx-libraries), because Gradle by default does not resolve this. I'm not MP user, so I wasn't aware of this format, so that's kinda on me, but I'd probably mention that in readme for non-MP people.
